directory = {
    "bmall": "Z:\\Properties\\Bozzuto\\Allure Apollo\\Invoices\\",
    "bmwa": "Z:\\Properties\\Bozzuto\\Winthrop Apartments\\Invoices\\",
    "bmah": "Z:\\Properties\\Bozzuto\\Anthem House\\Invoices\\",
    "bmasp": "Z:\\Properties\\Bozzuto\\Aspire Apollo\\Invoices\\",
    "bmwos": "Z:\\Properties\\Bozzuto\\Azure Oxford Square\\Invoices\\",
    "bmabc": "Z:\\Properties\\Bozzuto\\Arbors at Baltimore Crossroads\\Invoices\\",
    "bmap": "Z:\\Properties\\Bozzuto\\Arundel Preserve\\Invoices\\",
    "bmcc": "Z:\\Properties\\Bozzuto\\Cadence at Crown\\Invoices\\",
    "bmca": "Z:\\Properties\\Bozzuto\\Central Apartments\\Invoices\\",
    "bmcw": "Z:\\Properties\\Bozzuto\\Crosswinds @ A.T.C\\Invoices\\",
    "bmee": "Z:\\Properties\\Bozzuto\\Enclave at Emerson Apartments\\Invoices\\",
    "bmfen": "Z:\\Properties\\Bozzuto\\Fenwick\\Invoices\\",
    "bmtf": "Z:\\Properties\\Bozzuto\\Fitzgerald\\Invoices\\",
    "bmfay": "Z:\\Properties\\Bozzuto\\Flats 170 at Academy Yard\\Invoices\\",
    "bm8300": "Z:\\Properties\\Bozzuto\\Flats 8300\\Invoices\\",
    "bmfba": "Z:\\Properties\\Bozzuto\\Flats at Bethesda Avenue\\Invoices\\",
    "bmgtc": "Z:\\Properties\\Bozzuto\\Gramercy at Town Center\\Invoices\\",
    "bmhcs": "Z:\\Properties\\Bozzuto\\Hanover Cross Street\\Invoices\\",
    "bmhg": "Z:\\Properties\\Bozzuto\\Hunters Glen\\Invoices\\",
    "bmjr": "Z:\\Properties\\Bozzuto\\Jericho Residences\\Invoices\\",
    "bmla": "Z:\\Properties\\Bozzuto\\Lakehouse Residences\\Invoices\\",
    "bmph": "Z:\\Properties\\Bozzuto\\Pilot House at Riverdale Park\\Invoices\\",
    "bmmsq": "Z:\\Properties\\Bozzuto\\Mallory Square\\Invoices\\",
    "bmmb": "Z:\\Properties\\Bozzuto\\Mariner Bay\\Invoices\\",
    "bmmp": "Z:\\Properties\\Bozzuto\\Metropointe\\Invoices\\",
    "bmmk": "Z:\\Properties\\Bozzuto\\Millstone at Kingsview\\Invoices\\",
    "bmmv": "Z:\\Properties\\Bozzuto\\Monument Village\\Invoices\\",
    "bmhe": "Z:\\Properties\\Bozzuto\\Spinnaker Bay & Promenade\\Invoices\\",
    "bmsp": "Z:\\Properties\\Bozzuto\\St. Paul Senior Living\\Invoices\\",
    "bmstp": "Z:\\Properties\\Bozzuto\\Stone Point\\Invoices\\",
    "bmsc": "Z:\\Properties\\Bozzuto\\Strathmore\\Invoices\\",
    "bmberk": "Z:\\Properties\\Bozzuto\\The Berkleigh\\Invoices\\",
    "lbtb": "Z:\\Properties\\Bozzuto\\The Bowen (frmly Harmony Place)\\Invoices\\",
    "bmcd": "Z:\\Properties\\Bozzuto\\The Courts of Devon\\Invoices\\",
    "bmesp": "Z:\\Properties\\Bozzuto\\The Esplanade\\Invoices\\",
    "bmtl": "Z:\\Properties\\Bozzuto\\The Lindley\\Invoices\\",
    "bmmet": "Z:\\Properties\\Bozzuto\\The Metropolitan\\Invoices\\",
    "bmtm": "Z:\\Properties\\Bozzuto\\The Morgan\\Invoices\\",
    "bmthv": "Z:\\Properties\\Bozzuto\\The Townes at Harvest View\\Invoices\\",
    "bmva": "Z:\\Properties\\Bozzuto\\The Vine Apartments\\Invoices\\",
    "bmtw": "Z:\\Properties\\Bozzuto\\The Whitney\\Invoices\\",
    "bmtc": "Z:\\Properties\\Bozzuto\\Timberlawn Crescent\\Invoices\\",
    "bmuw": "Z:\\Properties\\Bozzuto\\Union Wharf\\Invoices\\",
    "bmtz": "Z:\\Properties\\Bozzuto\\Zenith\\Invoices\\",
    "bmraj": "Z:\\Properties\\Bozzuto\\The Residences at Annapolis Junction\\Invoices\\",
    "brh5074": "Z:\\Properties\\Berkshire Property Advisors\\Metro Place at Town Center\\Invoices\\",
    "brh2531": "Z:\\Properties\\Berkshire Property Advisors\\Berkshires at Town Center\\Invoices\\",
    "cjvms": "Z:\\Properties\\Corcoran Jennison\\The Villages at Marley Station\\Invoices\\",
    "gsbl": "Z:\\Properties\\Greystar\\Bayshore Landing\\Invoices\\",
    "gsbf": "Z:\\Properties\\Greystar\\Beech's Farm\\Invoices\\",
    "gesg": "Z:\\Properties\\Greystar\\Ellicott Grove\\Invoices\\",
    "gsgg": "Z:\\Properties\\Greystar\\Groveton Green\\Invoices\\",
    "gshss": "Z:\\Properties\\Greystar\\Heritage Silver Spring\\Invoices\\",
    "gslm": "Z:\\Properties\\Greystar\\Lakeside Mill\\Invoices\\",
    "gspco": "Z:\\Properties\\Greystar\\Paragon at Columbia\\Invoices\\",
    "gssh": "Z:\\Properties\\Greystar\\Sherwood Crossing\\Invoices\\",
    "gssf": "Z:\\Properties\\Greystar\\Southfield Apartments\\Invoices\\",
    "gscam": "Z:\\Properties\\Greystar\\The Cameron\\Invoices\\",
    "gshkp": "Z:\\Properties\\Greystar\\The Hamilton at Kings Place\\Invoices\\",
    "gset": "Z:\\Properties\\Greystar\\Elan Towson\\Invoices\\",
    "gs703": "Z:\\Properties\\Greystar\\Flats at 703\\Invoices\\",
    "gsmeb": "Z:\\Properties\\Greystar\\The Madison at Eden Brook\\Invoices\\",
    "gsubr": "Z:\\Properties\\Greystar\\Upstairs @ BR\\Invoices\\",
    "gots": "Z:\\Properties\\GoldOller\\The Seasons\\Invoices\\",
    "gost": "Z:\\Properties\\GoldOller\\Steeplechase\\Invoices\\",
    "pmfa": "Z:\\Properties\\Panco Management\\Foxfire Apartments\\Invoices\\",
    "pmtm": "Z:\\Properties\\Panco Management\\The Monterey\\Invoices\\",
    "pmpc": "Z:\\Properties\\Panco Management\\The Point at Crofton\\Invoices\\",
    "pmpe": "Z:\\Properties\\Panco Management\\The Point at Elkridge\\Invoices\\",
    "pmgs": "Z:\\Properties\\Panco Management\\The Point at Germantown Station\\Invoices\\",
    "pmpg": "Z:\\Properties\\Panco Management\\The Point at Germantown\\Invoices\\",
    "pmpll": "Z:\\Properties\\Panco Management\\The Point at Laurel Lakes\\Invoices\\",
    "pmpo": "Z:\\Properties\\Panco Management\\The Point at Odenton\\Invoices\\",
    "pmpom": "Z:\\Properties\\Panco Management\\The Point at Owings Mills\\Invoices\\",
    "pmso": "Z:\\Properties\\Panco Management\\The Point at Seven Oaks\\Invoices\\",
    "pmpwm": "Z:\\Properties\\Panco Management\\The Point at Watkins Mill\\Invoices\\",
    "pmpaw": "Z:\\Properties\\Panco Management\\The Point at Winterset\\Invoices\\",
    "ksi1305": "Z:\\Properties\\Kettler\\1305 Dock Street\\Invoices\\",
    "ksi1405": "Z:\\Properties\\Kettler\\1405 Point\\Invoices\\",
    "ksiao": "Z:\\Properties\\Kettler\\Avondale Overlook\\Invoices\\",
    "ksibv": "Z:\\Properties\\Kettler\\The Broadview\\Invoices\\",
    "ksifs": "Z:\\Properties\\Kettler\\Forrest Street\\Invoices\\",
    "ksirw": "Z:\\Properties\\Kettler\\Redwood\\Invoices\\",
    "ksifc": "Z:\\Properties\\Kettler\\The Fields of Rockville\\Invoices\\",
    "ksiwc": "Z:\\Properties\\Kettler\\The Fields of Silver Spring\\Invoices\\",
    "ksitg": "Z:\\Properties\\Kettler\\The Gunther\\Invoices\\"
    }
